spring:
  application:
    name: todos-webflux
# log levels: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, or OFF
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: '*'
