spring:
  application:
    name: todos-webflux
logging:
  level:
    io.corbs: DEBUG
server:
  port: 8010
management:
  endpoints:
    web:
      base-path: /ops
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
todos:
  webflux:
    limit: 25
