---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

inputs:
  - name: code-repo
  - name: version-repo

outputs:
  - name: build-artifacts

run:
  path: code-repo/ci/tasks/build.sh
