---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

params:
  - GROUP_ID:
  - ARTIFACT_ID:
  - ROUTE:

inputs:
  - name: code-repo
  - name: version

run:
  path: code-repo/ci/tasks/build-and-publish.sh
