---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

params:
  CF_MANIFEST_HOST:

inputs:
  - name: code-repo
  - name: version

outpus:
  - name: deployment

run:
  path: code-repo/ci/tasks/prepare-cf-push.sh
