---
resource_types:
  - name: artifactory-resource
    type: docker-image
    source:
      repository: springio/artifactory-resource
      tag: 0.0.10

resources:
  - name: code-repo
    type: git
    source:
      uri: ((code-repo-uri))
      branch: ((code-repo-branch))
      ignore_paths: ["ci"]

  - name: ci-scripts
    type: git
    source:
      uri: ((code-repo-uri))
      branch: ((code-repo-branch))
      paths: ["ci"]

  - name: version
    type: semver
    source:
      initial_version: 1.0.0-rc.0
      driver: git
      uri: ((version-repo-uri))
      branch: ((version-repo-branch))
      file: version
      private_key: ((version-repo-private-key))

#  - name: candidate-release
#    type: artifactory-resource
#    source:
#      uri: ((artifactory-uri))
#      username: ((artifactory-username))
#      password: ((artifactory-password))
#      build_name: ((artifactory-build-name))
#
#  - name: final-release
#    type: artifactory-resource
#    source:
#      uri: ((artifactory-uri))
#      username: ((artifactory-username))
#      password: ((artifactory-password))
#      build_name: ((artifactory-buildname))
#
  - name: cf-test
    type: cf
    source:
      api: ((cf-test-api))
      username: ((cf-test-username))
      password: ((cf-test-password))
      organization: ((cf-test-org))
      space: ((cf-test-space))

  - name: cf-prod
    type: cf
    source:
      api: ((cf-prod-api))
      username: ((cf-prod-username))
      password: ((cf-prod-password))
      organization: ((cf-prod-org))
      space: ((cf-prod-space))

jobs:
  - name: unit-test
    plan:
      - get: code-repo
        trigger: true
      - task: unit-test
        file: code-repo/ci/tasks/unit-test.yml

  - name: build-and-publish
    serial: true
    plan:
      - get: code-repo
        passed: [ unit-test ]
        trigger: true
      - get: ci-scripts
      - get: version
        params: { pre: rc }
      - task: build-and-publish
        file: ci-scripts/ci/tasks/build-and-publish.yml
        params:
          REPO_WITH_BINARIES: ((repo-with-binaries))
          REPO_WITH_BINARIES_FOR_UPLOAD: ((repo-with-binaries-for-upload))
          M2_SETTINGS_REPO_ID: ((m2-settings-repo-id))
          M2_SETTINGS_REPO_USERNAME: ((m2-settings-repo-username))
          M2_SETTINGS_REPO_PASSWORD: ((m2-settings-repo-password))
      - put: version
        params: { file: version/version }

  - name: deploy-to-test
    serial: true
    plan:
      - get: code-repo
        trigger: true
        passed: [ build-and-publish ]
      - get: ci-scripts
      - get: version
        passed: [ build-and-publish ]
      - task: prepare-cf-push
        file: ci-scripts/ci/tasks/prepare-cf-push.yml
        params:
          GROUP_ID: ((code-repo-group-id))
          ARTIFACT_ID: ((code-repo-artifact-id))
          ROUTE: ((cf-test-route))
          ARTIFACTORY_URL: ((repo-with-binaries))
      - put: cf-test
        params:
          manifest: deployment/manifest.yml

  - name: deploy-to-prod
    serial: true
    plan:
      - get: code-repo
        passed: [ deploy-to-test ]
      - get: ci-scripts
      - get: version
        passed: [ deploy-to-test ]
      - task: prepare-cf-push
        file: ci-scripts/ci/tasks/prepare-cf-push.yml
        params:
          GROUP_ID: ((code-repo-group-id))
          ARTIFACT_ID: ((code-repo-artifact-id))
          ROUTE: ((cf-prod-route))
          ARTIFACTORY_URL: ((repo-with-binaries))
      - put: cf-prod
        params:
          manifest: deployment/manifest.yml

  - name: prod-complete
    serial: true
    plan:
      - get: code-repo
        passed: [ deploy-to-prod ]
      - get: ci-scripts
        passed: [ deploy-to-prod ]
      - get: version
        params: { bump: final }
      - task: build-and-publish
        file: ci-scripts/ci/tasks/build-and-publish.yml
        params:
          REPO_WITH_BINARIES: ((repo-with-binaries))
          REPO_WITH_BINARIES_FOR_UPLOAD: ((repo-with-binaries-for-upload))
          M2_SETTINGS_REPO_ID: ((m2-settings-repo-id))
          M2_SETTINGS_REPO_USERNAME: ((m2-settings-repo-username))
          M2_SETTINGS_REPO_PASSWORD: ((m2-settings-repo-password))
      - put: version
        params: { file: version/version }

#  - name: major
#    serial_groups: [ version ]
#    plan:
#      - put: version
#        params: { bump: major, pre: rc }
#
#  - name: minor
#    serial_groups: [ version ]
#    plan:
#      - put: version
#        params: { bump: minor, pre: rc }
#
#  - name: patch
#    serial_groups: [ version ]
#    plan:
#      - get: version
#        passed: [ ship-it ]
#        trigger: true
#      - put: version
#        params: { bump: patch, pre: rc }
